apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "owntracks-exporter.fullname" . }}
  labels:
    # NON-DEFAULT: We also care about knowing the version of the app.
    app.kubernetes.io/version: "{{ .Chart.AppVersion }}"
{{ include "owntracks-exporter.labels" . | indent 4 }}
data:
{{- range $key, $value := .Values.config.env }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
